// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package generator

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDf83c95dDecodeGithubComHoher2000SchoolTrendsGenerator(in *jlexer.Lexer, out *Script) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "full_text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FullText = string(in.String())
			}
		case "subtitles":
			if in.IsNull() {
				in.Skip()
				out.Subtitles = nil
			} else {
				in.Delim('[')
				if out.Subtitles == nil {
					if !in.IsDelim(']') {
						out.Subtitles = make([]string, 0, 4)
					} else {
						out.Subtitles = []string{}
					}
				} else {
					out.Subtitles = (out.Subtitles)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Subtitles = append(out.Subtitles, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "skip":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Skip = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDf83c95dEncodeGithubComHoher2000SchoolTrendsGenerator(out *jwriter.Writer, in Script) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"full_text\":"
		out.RawString(prefix[1:])
		out.String(string(in.FullText))
	}
	{
		const prefix string = ",\"subtitles\":"
		out.RawString(prefix)
		if in.Subtitles == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Subtitles {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	if in.Skip {
		const prefix string = ",\"skip\":"
		out.RawString(prefix)
		out.Bool(bool(in.Skip))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Script) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDf83c95dEncodeGithubComHoher2000SchoolTrendsGenerator(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Script) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDf83c95dEncodeGithubComHoher2000SchoolTrendsGenerator(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Script) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDf83c95dDecodeGithubComHoher2000SchoolTrendsGenerator(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Script) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDf83c95dDecodeGithubComHoher2000SchoolTrendsGenerator(l, v)
}
