// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tts

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson73075cb4DecodeGithubComHoher2000SchoolTrendsTts(in *jlexer.Lexer, out *TokenResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "access_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccessToken = string(in.String())
			}
		case "expires_in":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExpiresIn = int(in.Int())
			}
		case "refresh_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RefreshToken = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson73075cb4EncodeGithubComHoher2000SchoolTrendsTts(out *jwriter.Writer, in TokenResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"access_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccessToken))
	}
	{
		const prefix string = ",\"expires_in\":"
		out.RawString(prefix)
		out.Int(int(in.ExpiresIn))
	}
	{
		const prefix string = ",\"refresh_token\":"
		out.RawString(prefix)
		out.String(string(in.RefreshToken))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TokenResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson73075cb4EncodeGithubComHoher2000SchoolTrendsTts(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TokenResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson73075cb4EncodeGithubComHoher2000SchoolTrendsTts(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TokenResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson73075cb4DecodeGithubComHoher2000SchoolTrendsTts(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TokenResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson73075cb4DecodeGithubComHoher2000SchoolTrendsTts(l, v)
}
func easyjson73075cb4DecodeGithubComHoher2000SchoolTrendsTts1(in *jlexer.Lexer, out *SavedToken) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "access_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccessToken = string(in.String())
			}
		case "refresh_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RefreshToken = string(in.String())
			}
		case "expires_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.ExpiresAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson73075cb4EncodeGithubComHoher2000SchoolTrendsTts1(out *jwriter.Writer, in SavedToken) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"access_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccessToken))
	}
	{
		const prefix string = ",\"refresh_token\":"
		out.RawString(prefix)
		out.String(string(in.RefreshToken))
	}
	{
		const prefix string = ",\"expires_at\":"
		out.RawString(prefix)
		out.Raw((in.ExpiresAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SavedToken) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson73075cb4EncodeGithubComHoher2000SchoolTrendsTts1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SavedToken) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson73075cb4EncodeGithubComHoher2000SchoolTrendsTts1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SavedToken) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson73075cb4DecodeGithubComHoher2000SchoolTrendsTts1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SavedToken) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson73075cb4DecodeGithubComHoher2000SchoolTrendsTts1(l, v)
}
